config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :option_names
  end
  namespace :admin do
    resources :fci_skus
    resources :fci_button_buys
    resources :fci_quantities
    resources :fci_prices
    resources :carts
    resources :orders
    resources :line_items
  end
  resources :line_items
  resources :orders
  resources :carts
  get 'line_items/:id/cart_plus' => 'line_items#cart_plus', as: 'cart_plus'
  get 'line_items/:id/cart_minus' => 'line_items#cart_minus', as: 'cart_minus'
end

app/models/fci_price.rb
class FciPrice < ApplicationRecord
  belongs_to :fci
  before_save :zero_price

  def zero_price
    if self.value.nil?
      self.value == 0
    end
  end
end

app/controllers/admin/fci_prices_controller.rb
class Admin::FciPricesController < Admin::BaseController
  before_action :set_fci_price, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource
  layout 'admin'
  # GET /admin/fci_prices
  def index
    @fci_prices = FciPrice.all
  end

  # GET /admin/fci_prices/1
  def show
  end

  # GET /admin/fci_prices/new
  def new
    @fci_price = FciPrice.new
  end

  # GET /admin/fci_prices/1/edit
  def edit
  end

  # POST /admin/fci_prices
  def create
    @fci_price = FciPrice.new(fci_price_params)

    if @fci_price.save
      redirect_to [:admin, @fci_price], notice: 'Fci price was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /admin/fci_prices/1
  def update
    if @fci_price.update(fci_price_params)
      redirect_to [:admin, @fci_price], notice: 'Fci price was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /admin/fci_prices/1
  def destroy
    @fci_price.destroy
    redirect_to admin_fci_prices_url, notice: 'Fci price was successfully destroyed.'
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_fci_price
    @fci_price = FciPrice.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def fci_price_params
    params.require(:fci_price).permit(:value, :currency, :buy, :name_buy, :fci_id, :mid, :model)
  end
end

app/helpers/admin/fci_prices_helper.rb
module Admin::FciPricesHelper
end

app/views/admin/fci_prices/_form.html.erb
<%= form_for([:admin, @fci_price]) do |f| %>
    <% if @fci_price.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@fci_price.errors.count, "error") %> prohibited this fci_price from being saved:</h2>

          <ul>
            <% @fci_price.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :value %><br>
      <%= f.text_field :value %>
    </div>
    <div class="field">
      <%= f.label :currency %><br>
      <%= f.text_field :currency %>
    </div>
    <div class="field">
      <%= f.label :buy %><br>
      <%= f.check_box :buy %>
    </div>
    <div class="field">
      <%= f.label :name_buy %><br>
      <%= f.text_field :name_buy %>
    </div>
    <div class="field">
      <%= f.label :fci_id %><br>
      <%= f.text_field :fci_id %>
    </div>
    <div class="field">
      <%= f.label :mid %><br>
      <%= f.number_field :mid %>
    </div>
    <div class="field">
      <%= f.label :model %><br>
      <%= f.text_field :model %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/admin/fci_prices/_form_field.html.erb
<% if FciPrice.where(fci_id: @fci.id, model: @model.model_name.human, mid: @model.id).empty? %>
    <div class="form-group">
      <label class="col-md-3 control-label"><%= @fci.name %></label>
      <div class="col-md-9">
        <div class="col-md-6">
          <%= number_field_tag ":fci_price_value"+@fci.machine_name, step: :any, class: 'form-control' %>
        </div>
        <div class="col-md-6">
          <%= select_tag(":fci_price_currency"+@fci.machine_name, options_for_select(available_currency, default_currency), class: 'form-control') %>
        </div>
        <span class="help-block"> <br/>  </span>
      </div>
    </div>
<% else %>
    <% FciPrice.where(fci_id: @fci.id, model: @model.model_name.human, mid: @model.id).each do |decimal| %>
        <div class="form-group">
          <label class="col-md-3 control-label"><%= @fci.name %></label>
          <div class="col-md-9">
            <div class="col-md-6">
              <%= number_field_tag ":fci_price_value"+@fci.machine_name, decimal.value, step: :any, class: 'form-control' %>
            </div>
            <div class="col-md-6">
              <%= select_tag(":fci_price_currency"+@fci.machine_name, options_for_select(available_currency, decimal.currency||default_currency), class: 'form-control') %>
            </div>
            <span class="help-block"> <br/>  </span>
          </div>
        </div>
    <% end %>
<% end %>

app/views/admin/fci_prices/edit.html.erb
<h1>Editing fci_price</h1>

<%= render 'form' %>

<%= link_to 'Show', [:admin, @fci_price] %> |
<%= link_to 'Back', admin_fci_prices_path %>

app/views/admin/fci_prices/index.html.erb
<h1>Listing fci_prices</h1>

<table>
  <thead>
  <tr>
    <th>Value</th>
    <th>Currency</th>
    <th>Buy</th>
    <th>Name buy</th>
    <th>Fci</th>
    <th>Mid</th>
    <th>Model</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
  </thead>

  <tbody>
  <% @fci_prices.each do |fci_price| %>
      <tr>
        <td><%= fci_price.value %></td>
        <td><%= fci_price.currency %></td>
        <td><%= fci_price.buy %></td>
        <td><%= fci_price.name_buy %></td>
        <td><%= fci_price.fci %></td>
        <td><%= fci_price.mid %></td>
        <td><%= fci_price.model %></td>
        <td><%= link_to 'Show', [:admin, fci_price] %></td>
        <td><%= link_to 'Edit', edit_admin_fci_price_path(fci_price) %></td>
        <td><%= link_to 'Destroy', [:admin, fci_price], method: :delete, data: {confirm: 'Are you sure?'} %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Fci price', new_admin_fci_price_path %>

app/views/admin/fci_prices/new.html.erb
<h1>New fci_price</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_fci_prices_path %>

app/views/admin/fci_prices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Value:</strong>
  <%= @fci_price.value %>
</p>

<p>
  <strong>Currency:</strong>
  <%= @fci_price.currency %>
</p>

<p>
  <strong>Buy:</strong>
  <%= @fci_price.buy %>
</p>

<p>
  <strong>Name buy:</strong>
  <%= @fci_price.name_buy %>
</p>

<p>
  <strong>Fci:</strong>
  <%= @fci_price.fci %>
</p>

<p>
  <strong>Mid:</strong>
  <%= @fci_price.mid %>
</p>

<p>
  <strong>Model:</strong>
  <%= @fci_price.model %>
</p>

<%= link_to 'Edit', edit_admin_fci_price_path(@fci_price) %> |
<%= link_to 'Back', admin_fci_prices_path %>