config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :option_names
  end
  namespace :admin do
    resources :fci_skus
    resources :fci_button_buys
    resources :fci_quantities
    resources :fci_prices
    resources :carts
    resources :orders
    resources :line_items
  end
  resources :line_items
  resources :orders
  resources :carts
  get 'line_items/:id/cart_plus' => 'line_items#cart_plus', as: 'cart_plus'
  get 'line_items/:id/cart_minus' => 'line_items#cart_minus', as: 'cart_minus'
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :record_type
  belongs_to :user
  has_many :model_relations, -> { where model_main: 'Cart' }, :foreign_key => 'mid_main', dependent: :destroy
  has_many :fcis, through: :record_type
  has_many :line_items
  has_many :orders
  after_save :set_record_type
  after_save :set_entity
  #after_save :in_order
  after_save :calc_skidka
  default_scope { order("created_at DESC") }

  def set_record_type
    if self.record_type_id.nil?
      self.record_type_id=RecordType.find_by_machine_name(:cart).id
    end
  end

  def set_entity
    unless self.record_type_id.nil?
      if self.entity.nil?
        self.entity = self.record_type.machine_name
      end
    end
  end

  def in_order
    if status_changed?
      if status == 'ping'
        order = Order.create(status: 'ping', user_id: user_id, cart_id: id)
        line_items.map{|ln| ln.update(order_id: order.id)}
      end
    end
  end

  def calc_skidka
    if status == 'new' and !user_id.nil? and !line_items.empty?
      client = Savon::Client.new(wsdl: 'http://149.202.222.162:80/base3s_admin_c/ws/WebSite.1cws?wsdl', basic_auth: ["callcenter", "Rfrf<zrf"])
      kodc = user.profile.kodcs.take.value
      nomerd = user.profile.nomer_dogovoras.take.value
      p = line_items.map{|line| "{'UIDClient': '', 'CodeClient': '#{kodc}' 'NameClient': '', 'UIDDogovor': '', 'CodeDogovor': '#{nomerd}', 'NameDogovor': '', 'UIDTovar': '', 'CodeTovar': '#{line.product.kods.take.value}', 'NameTovar': '', 'quantity': '#{line.total_quantity}', 'Price': '#{line.total_price}', 'SostoyanieZakaza': '', 'NumberOfOrderOnSite': '', 'isDropshipping': false, 'PriceDropshipping': 0, 'UIDAdress': '', 'NameAdress': '','CodeAdress': '', 'TypeOfDelivery': ''}"}
      pj = p.to_s.gsub('"', '')
      response = client.call(:order_price, message: {"JSON_goods_order"=>"{'#value': "+pj+"}", "NumberOfOrderOnSite"=>''})
      comone = response.body[:order_price_response][:return]
      parsed = JSON.parse(comone)["#value"]
      parsed.each do |prod|
        kodp = prod['CodeTovar']
        line_items.map{|e| @kodp = e if e.product.kods.take.value.to_s == kodp}
        totalp = prod['Price']*@kodp.total_quantity
        currency = @kodp.product.tsenas.take.currency
        case currency
          when 'USD'
            @uatotal = totalp*26.40
          when 'EUR'
            @uatotal = totalp*29.55
          when 'UAH'
            @uatotal = totalp
          when 'CZK'
            @uatotal = totalp*27.04
          when 'RUR'
            @uatotal = totalp*0.46
          else
            @uatotal = totalp
        end

        @kodp.update(total_price: @uatotal, oneprice: prod['Price'])

      end

    end
  end

end

app/controllers/admin/carts_controller.rb
class Admin::CartsController < Admin::BaseController
  before_action :set_cart, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource
  layout 'admin'
  # GET /admin/carts
  def index
    @carts = Cart.all
  end

  # GET /admin/carts/1
  def show
  end

  # GET /admin/carts/new
  def new
    @cart = Cart.new
  end

  # GET /admin/carts/1/edit
  def edit
  end

  # POST /admin/carts
  def create
    @cart = Cart.new(cart_params)

    if @cart.save
      redirect_to [:admin, @cart], notice: 'Cart was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /admin/carts/1
  def update
    if @cart.update(cart_params)
      instance_saver(@cart, params)
      redirect_to [:admin, @cart], notice: 'Cart was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /admin/carts/1
  def destroy
    @cart.destroy
    redirect_to admin_carts_url, notice: 'Cart was successfully destroyed.'
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_cart
    @cart = Cart.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def cart_params
    params.require(:cart).permit(:status, :record_type_id, :user_id)
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: [:show, :edit, :update, :destroy]

  # GET /carts
  def index
    if current_user.present?
      @carts = Cart.where(status: 'new', user_id: current_user.id)
    else
      @carts = Cart.where(id: session[:cart_id])
    end
  end

  # GET /carts/1
  def show
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts
  def create
    @cart = Cart.new(cart_params)

    if @cart.save
      redirect_to @cart, notice: 'Cart was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /carts/1
  def update
    if @cart.update(cart_params)
      instance_saver(@cart, params)
      redirect_to carts_url, notice: 'Ваша корзина №'+@cart.id.to_s+' была обновлена.'
    else
      render :edit
    end
  end

  # DELETE /carts/1
  def destroy
    @cart.destroy
    redirect_to carts_url, notice: 'Cart was successfully destroyed.'
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_cart
    @cart = Cart.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def cart_params
    params.require(:cart).permit(:status, :record_type_id, :user_id)
  end
end

app/helpers/admin/carts_helper.rb
module Admin::CartsHelper
end

app/helpers/carts_helper.rb
module CartsHelper

  def current_cart
    Cart.find(session[:cart_id])
    rescue ActiveRecord::RecordNotFound
      session.delete(:cart_id)
  end

  def current_cart_price(format)
    unless current_cart.nil?
      summa = current_cart.line_items.sum("total_price")
      case format
        when 'currency'
          case default_currency
            when 'USD'
              '$'+summa.to_s
            when 'UAH'
              summa.to_s+' грн.'
          end
        when 'nil'
          summa
      end
    else
      0.00
    end
  end

  def current_cart_qua
    unless current_cart.nil?
      current_cart.line_items.sum("total_quantity")
    else
      0.00
    end
  end

end

app/views/carts/_form.html.erb
<%= form_for(@cart) do |f| %>
    <% if @cart.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

          <ul>
            <% @cart.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :status %><br>
      <%= f.text_field :status %>
    </div>
    <div class="field">
      <%= f.label :record_type_id %><br>
      <%= f.number_field :record_type_id %>
    </div>
    <div class="field">
      <%= f.label :user_id %><br>
      <%= f.text_field :user_id %>
    </div>

    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/carts/edit.html.erb
<h1>Editing Cart</h1>

<%= render 'form' %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

app/views/carts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Carts</h1>

<table>
  <thead>
  <tr>
    <th>Status</th>
    <th>Record type</th>
    <th>User</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @carts.each do |cart| %>
      <tr>
        <td><%= cart.status %></td>
        <td><%= cart.record_type %></td>
        <td><%= cart.user %></td>
        <td><%= link_to 'Show', cart %></td>
        <td><%= link_to 'Edit', edit_cart_path(cart) %></td>
        <td><%= link_to 'Destroy', cart, method: :delete, data: {confirm: 'Are you sure?'} %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cart', new_cart_path %>

app/views/carts/new.html.erb
<h1>New Cart</h1>

<%= render 'form' %>

<%= link_to 'Back', carts_path %>

app/views/carts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Status:</strong>
  <%= @cart.status %>
</p>

<p>
  <strong>Record type:</strong>
  <%= @cart.record_type %>
</p>

<p>
  <strong>User:</strong>
  <%= @cart.user %>
</p>

<%= link_to 'Edit', edit_cart_path(@cart) %> |
<%= link_to 'Back', carts_path %>