config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :option_names
  end
  namespace :admin do
    resources :fci_skus
    resources :fci_button_buys
    resources :fci_quantities
    resources :fci_prices
    resources :carts
    resources :orders
    resources :line_items
  end
  resources :line_items
  resources :orders
  resources :carts
  get 'line_items/:id/cart_plus' => 'line_items#cart_plus', as: 'cart_plus'
  get 'line_items/:id/cart_minus' => 'line_items#cart_minus', as: 'cart_minus'
end

app/models/option_name.rb
class OptionName < ApplicationRecord
  has_many :option_values
  has_many :option_relatives
end

app/controllers/admin/option_names_controller.rb
class Admin::OptionNamesController < ApplicationController
  before_action :set_option_name, only: [:show, :edit, :update, :destroy]

  # GET /admin/option_names
  def index
    @option_names = OptionName.all
  end

  # GET /admin/option_names/1
  def show
  end

  # GET /admin/option_names/new
  def new
    @option_name = OptionName.new
  end

  # GET /admin/option_names/1/edit
  def edit
  end

  # POST /admin/option_names
  def create
    @option_name = OptionName.new(option_name_params)

    if @option_name.save
      redirect_to [:admin, @option_name], notice: 'Option name was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /admin/option_names/1
  def update
    if @option_name.update(option_name_params)
      redirect_to [:admin, @option_name], notice: 'Option name was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /admin/option_names/1
  def destroy
    @option_name.destroy
    redirect_to admin_option_names_url, notice: 'Option name was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_option_name
      @option_name = OptionName.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def option_name_params
      params.require(:option_name).permit(:name, :type, :value, :active, :position)
    end
end

app/helpers/admin/option_names_helper.rb
module Admin::OptionNamesHelper
end

app/views/admin/option_names/_form.html.erb
<%= form_for([:admin, @option_name], html: { class: 'form-horizontal option_name' }) do |f| %>
  <% if @option_name.errors.any? %>
    <div id="error_explanation" class="panel panel-danger">
      <div class="panel-heading">
        <h2 class="panel-title"><%= pluralize(@option_name.errors.count, "error") %> prohibited this option_name from being saved:</h2>
      </div>
      <div class="panel-body">
        <ul>
        <% @option_name.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, class: 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :name, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :type, class: 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :type, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :value, class: 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_area :value, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-md-offset-2 col-md-10">
      <%= f.label :active, for: nil do %>
        <%= f.check_box :active %>
        <%= OptionName.human_attribute_name(:active) %>
      <% end %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :position, class: 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.number_field :position, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-md-offset-2 col-md-10">
      <%= f.submit nil, class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>

app/views/admin/option_names/edit.html.erb
<div class="page-header">
  <h1>Editing option_name</h1>
</div>

<%= render 'form' %>

<%= link_to 'Show', [:admin, @option_name], class: 'btn btn-default' %>
<%= link_to 'Back', admin_option_names_path, class: 'btn btn-default' %>

app/views/admin/option_names/index.html.erb
<div class="page-header">
  <h1>Listing option_names</h1>
</div>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Type</th>
      <th>Value</th>
      <th>Active</th>
      <th>Position</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @option_names.each do |option_name| %>
      <tr>
        <td><%= option_name.name %></td>
        <td><%= option_name.type %></td>
        <td><%= option_name.value %></td>
        <td><%= option_name.active %></td>
        <td><%= option_name.position %></td>
        <td><%= link_to 'Show', [:admin, option_name], class: 'btn btn-default btn-xs' %></td>
        <td><%= link_to 'Edit', edit_admin_option_name_path(option_name), class: 'btn btn-default btn-xs' %></td>
        <td><%= link_to 'Destroy', [:admin, option_name], method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-xs btn-danger' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Option name', new_admin_option_name_path, class: 'btn btn-primary' %>

app/views/admin/option_names/new.html.erb
<div class="page-header">
  <h1>New option_name</h1>
</div>

<%= render 'form' %>

<%= link_to 'Back', admin_option_names_path, class: 'btn btn-default' %>

app/views/admin/option_names/show.html.erb
<p id="notice"><%= notice %></p>

<dl class="dl-horizontal">
  <dt><strong>Name:</strong></dt>
  <dd><%= @option_name.name %></dd>
</dl>

<dl class="dl-horizontal">
  <dt><strong>Type:</strong></dt>
  <dd><%= @option_name.type %></dd>
</dl>

<dl class="dl-horizontal">
  <dt><strong>Value:</strong></dt>
  <dd><%= @option_name.value %></dd>
</dl>

<dl class="dl-horizontal">
  <dt><strong>Active:</strong></dt>
  <dd><%= @option_name.active %></dd>
</dl>

<dl class="dl-horizontal">
  <dt><strong>Position:</strong></dt>
  <dd><%= @option_name.position %></dd>
</dl>

<%= link_to 'Edit', edit_admin_option_name_path(@option_name), class: 'btn btn-default' %>
<%= link_to 'Back', admin_option_names_path, class: 'btn btn-default' %>