config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :option_names
  end
  namespace :admin do
    resources :fci_skus
    resources :fci_button_buys
    resources :fci_quantities
    resources :fci_prices
    resources :carts
    resources :orders
    resources :line_items
  end
  resources :line_items
  resources :orders
  resources :carts
  get 'line_items/:id/cart_plus' => 'line_items#cart_plus', as: 'cart_plus'
  get 'line_items/:id/cart_minus' => 'line_items#cart_minus', as: 'cart_minus'
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :order
  belongs_to :cart
  belongs_to :record_type
  has_many :model_relations, -> { where model_main: 'LineItem' }, :foreign_key => 'mid_main', dependent: :destroy
  has_many :fcis, through: :record_type
  belongs_to :tovar, :class_name => "Cell", :foreign_key => 'mid'

  default_scope { order("created_at DESC") }
  before_create :set_record_type
  before_create :set_entity
  before_create :set_status
  before_save :set_price

  def set_record_type
    if self.record_type_id.nil?
      self.record_type_id=RecordType.find_by_machine_name(:line_item).id
    end
  end

  def set_entity
    unless self.record_type_id.nil?
      if self.entity.nil?
        self.entity = self.record_type.machine_name
      end
    end
  end

  def set_status
    if self.status.nil?
      self.status='new'
    end
  end


  def set_price
    unless self.mid and self.model and self.total_quantity == nil
      fieldc_price = FieldCustom.find_by_machine_name(:fci_prices)
      product = self.model.constantize.find(self.mid)
      if product.fcis.find_by(field_custom_id: fieldc_price.id).nil?
        role_price = false
        product.cells.each(public: true) do |cell|
          cell_price = cell.fcis.find_by(field_custom_id: fieldc_price.id)
          unless cell_price.nil?
            role_field = FciInteger.find_by(model: 'Cell', mid: cell.id)
            if User.current.nil?
              product.cells.each(public: true) do |cell|
                cell_price = cell.fcis.find_by(field_custom_id: fieldc_price.id)
                unless cell_price.nil?
                  role_field = FciInteger.find_by(model: 'Cell', mid: cell.id)
                  if role_field.value == 3
                    field_price = FciPrice.find_by(model: 'Cell', mid: cell.id)
                    self.oneprice= field_price.value if self.oneprice == 0
                    total_price = self.total_quantity * self.oneprice
                    currency = self.product.tsenas.take.currency
                    case currency
                      when 'USD'
                        @uatotal = total_price*26.40
                      when 'EUR'
                        @uatotal = total_price*29.55
                      when 'UAH'
                        @uatotal = total_price
                      when 'CZK'
                        @uatotal = total_price*27.04
                      when 'RUR'
                        @uatotal = total_price*0.46
                      else
                        @uatotal = total_price
                    end
                    self.total_price = @uatotal
                  end
                end
              end
            else
              User.current.roles.each do |role|
                if role_field.value == role.id
                  role_price = true
                  field_price = FciPrice.find_by(model: 'Cell', mid: cell.id)
                  self.oneprice= field_price.value if self.oneprice == 0
                  total_price = self.total_quantity * self.oneprice
                  currency = self.product.tsenas.take.currency
                  case currency
                    when 'USD'
                      @uatotal = total_price*26.40
                    when 'EUR'
                      @uatotal = total_price*29.55
                    when 'UAH'
                      @uatotal = total_price
                    when 'CZK'
                      @uatotal = total_price*27.04
                    when 'RUR'
                      @uatotal = total_price*0.46
                    else
                      @uatotal = total_price
                  end
                  self.total_price = @uatotal
                end
              end
            end
          end
        end
        if role_price == false
          product.cells.each(public: true) do |cell|
            cell_price = cell.fcis.find_by(field_custom_id: fieldc_price.id)
            unless cell_price.nil?
              role_field = FciInteger.find_by(model: 'Cell', mid: cell.id)
              if role_field.value == 3
                field_price = FciPrice.find_by(model: 'Cell', mid: cell.id)
                self.oneprice= field_price.value if self.oneprice == 0
                total_price = self.total_quantity * self.oneprice
                currency = self.product.tsenas.take.currency
                case currency
                  when 'USD'
                    @uatotal = total_price*26.40
                  when 'EUR'
                    @uatotal = total_price*29.55
                  when 'UAH'
                    @uatotal = total_price
                  when 'CZK'
                    @uatotal = total_price*27.04
                  when 'RUR'
                    @uatotal = total_price*0.46
                  else
                    @uatotal = total_price
                end
                self.total_price = @uatotal
              end
            end
          end
        end
      else
        field_price = FciPrice.find_by(model: self.model, mid: self.mid)
        self.oneprice= field_price.value if self.oneprice == 0
        total_price = self.total_quantity * self.oneprice
        currency = self.product.tsenas.take.currency
        case currency
          when 'USD'
            @uatotal = total_price*26.40
          when 'EUR'
            @uatotal = total_price*29.55
          when 'UAH'
            @uatotal = total_price
          when 'CZK'
            @uatotal = total_price*27.04
          when 'RUR'
            @uatotal = total_price*0.46
          else
            @uatotal = total_price
        end
        self.total_price = @uatotal
      end
    end
  end

  def product
    model.constantize.find(mid)
  end

end

app/controllers/admin/line_items_controller.rb
class Admin::LineItemsController < Admin::BaseController
  before_action :set_line_item, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource
  layout 'admin'
  # GET /admin/line_items
  def index
    @line_items = LineItem.all
  end

  # GET /admin/line_items/1
  def show
  end

  # GET /admin/line_items/new
  def new
    @line_item = LineItem.new
  end

  # GET /admin/line_items/1/edit
  def edit
  end

  # POST /admin/line_items
  def create
    @line_item = LineItem.new(line_item_params)

    if @line_item.save
      redirect_to [:admin, @line_item], notice: 'Line item was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /admin/line_items/1
  def update
    if @line_item.update(line_item_params)
      instance_saver(@line_item, params)
      redirect_to [:admin, @line_item], notice: 'Line item was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /admin/line_items/1
  def destroy
    @line_item.destroy
    redirect_to admin_line_items_url, notice: 'Line item was successfully destroyed.'
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_line_item
    @line_item = LineItem.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def line_item_params
    params.require(:line_item).permit(:total_price, :total_quantity, :status, :record_type_id, :mid, :model, :order_id, :cart_id, :oneprice)
  end
end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
  skip_before_filter :verify_authenticity_token
  before_action :set_line_item, only: [:show, :edit, :update, :destroy, :cart_plus, :cart_minus]

  # GET /line_items
  def index
    @line_items = LineItem.all
  end

  def cart_plus
    qua = @line_item.total_quantity += 1
    @line_item.update(total_quantity: qua)
    redirect_to :back, notice: 'Вы обновили корзину!'
  end

  def cart_minus
    qua = @line_item.total_quantity -= 1
    @line_item.update(total_quantity: qua)
    redirect_to :back, notice: 'Вы обновили корзину!'
  end

  # GET /line_items/1
  def show
  end

  # GET /line_items/new
  def new
    @line_item = LineItem.new
  end

  # GET /line_items/1/edit
  def edit
  end

  # POST /line_items
  def create
    if session[:cart_id]
      @cart = Cart.find_by(id: session[:cart_id], status: :new)
      if @cart.nil?
        if current_user.nil?
          @rtcart=RecordType.find_by_machine_name(:cart)
          @cart = Cart.create(record_type_id: @rtcart.id, entity: :cart, status: :new)
          session[:cart_id] = @cart.id
        else
          @cart = Cart.find_by(user_id: current_user.id, status: :new)
          if @cart.nil?
            @rtcart=RecordType.find_by_machine_name(:cart)
            @cart = Cart.create(record_type_id: @rtcart.id, entity: :cart, status: :new, user_id: current_user.id)
          end
          session[:cart_id] = @cart.id
        end
      end
    else
      if current_user.nil?
        @rtcart=RecordType.find_by_machine_name(:cart)
        @cart = Cart.create(record_type_id: @rtcart.id, entity: :cart, status: :new)
        session[:cart_id] = @cart.id
      else
        @cart = Cart.find_by(user_id: current_user.id, status: :new)
        if @cart.nil?
          @rtcart=RecordType.find_by_machine_name(:cart)
          @cart = Cart.create(record_type_id: @rtcart.id, entity: :cart, status: :new, user_id: current_user.id)
        end
        session[:cart_id] = @cart.id
      end
    end
    if params[:items].present?
      params[:items].each do |item|
        unless item[:total_quantity] == 0
          current_line = LineItem.find_by(cart_id: @cart.id, record_type_id: params[:line_item][:record_type_id], mid: item[:mid], model: item[:model])
          if current_line
            qua = current_line.total_quantity + item[:total_quantity].to_i
            current_line.update(total_quantity: qua)
          else
            @line_item = LineItem.new(cart_id: @cart.id, record_type_id: params[:line_item][:record_type_id], mid: item[:mid], model: item[:model], total_quantity: item[:total_quantity].to_i)
            instance_saver(@line_item, params)
            @line_item.update(cart_id: session[:cart_id].to_i)
          end
        end
      end
    else
      current_line = LineItem.find_by(cart_id: @cart.id, record_type_id: params[:line_item][:record_type_id], mid: params[:line_item][:mid], model: params[:line_item][:model])
      if current_line
        qua = current_line.total_quantity + params[:line_item][:total_quantity].to_i
        current_line.update(total_quantity: qua)
      else
        @line_item = LineItem.new(line_item_params)
        instance_saver(@line_item, params)
        @line_item.update(cart_id: session[:cart_id].to_i)
      end
    end
    redirect_to :back, notice: 'Вы добавили товар в корзину!'
  end

  # PATCH/PUT /line_items/1
  def update
    if @line_item.update(line_item_params)
      instance_saver(@line_item, params)

      redirect_to @line_item, notice: 'Line item was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /line_items/1
  def destroy
    @line_item.destroy
    redirect_to :back, :gflash => {:success => 'Вы удалили товар из заказа'}
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_line_item
    @line_item = LineItem.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def line_item_params
    params.require(:line_item).permit(:total_price, :total_quantity, :status, :record_type_id, :mid, :model, :order_id, :cart_id, :oneprice)
  end
end

app/helpers/admin/line_items_helper.rb
module Admin::LineItemsHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
  def line_item_new
    LineItem.new
  end

  def line_item_price(item,format)
      summa = item.total_price
      case format
        when 'currency'
          case default_currency
            when 'USD'
              '$'+summa.to_s
            when 'UAH'
              summa.to_s+' грн.'
          end
        when 'nil'
          summa
      end
  end


  def line_item_product(item)
    item.model.constantize.find(item.mid.to_i)
  end

end

app/views/line_items/_form.html.erb
<%= form_for(@line_item) do |f| %>
    <% if @line_item.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@line_item.errors.count, "error") %> prohibited this line_item from being saved:</h2>

          <ul>
            <% @line_item.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :total_price %><br>
      <%= f.text_field :total_price %>
    </div>
    <div class="field">
      <%= f.label :total_quantity %><br>
      <%= f.text_field :total_quantity %>
    </div>
    <div class="field">
      <%= f.label :status %><br>
      <%= f.text_field :status %>
    </div>
    <div class="field">
      <%= f.label :record_type_id %><br>
      <%= f.number_field :record_type_id %>
    </div>
    <div class="field">
      <%= f.label :mid %><br>
      <%= f.text_field :mid %>
    </div>
    <div class="field">
      <%= f.label :model %><br>
      <%= f.text_field :model %>
    </div>
    <div class="field">
      <%= f.label :order_id %><br>
      <%= f.text_field :order_id %>
    </div>
    <div class="field">
      <%= f.label :cart_id %><br>
      <%= f.text_field :cart_id %>
    </div>

    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/line_items/edit.html.erb
<h1>Editing Line Item</h1>

<%= render 'form' %>

<%= link_to 'Show', @line_item %> |
<%= link_to 'Back', line_items_path %>

app/views/line_items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Line Items</h1>

<table>
  <thead>
  <tr>
    <th>Total price</th>
    <th>Total quantity</th>
    <th>Status</th>
    <th>Record type</th>
    <th>Mid</th>
    <th>Model</th>
    <th>Order</th>
    <th>Cart</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @line_items.each do |line_item| %>
      <tr>
        <td><%= line_item.total_price %></td>
        <td><%= line_item.total_quantity %></td>
        <td><%= line_item.status %></td>
        <td><%= line_item.record_type %></td>
        <td><%= line_item.mid %></td>
        <td><%= line_item.model %></td>
        <td><%= line_item.order %></td>
        <td><%= line_item.cart %></td>
        <td><%= link_to 'Show', line_item %></td>
        <td><%= link_to 'Edit', edit_line_item_path(line_item) %></td>
        <td><%= link_to 'Destroy', line_item, method: :delete, data: {confirm: 'Are you sure?'} %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Line item', new_line_item_path %>

app/views/line_items/new.html.erb
<h1>New Line Item</h1>

<%= render 'form' %>

<%= link_to 'Back', line_items_path %>

app/views/line_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Total price:</strong>
  <%= @line_item.total_price %>
</p>

<p>
  <strong>Total quantity:</strong>
  <%= @line_item.total_quantity %>
</p>

<p>
  <strong>Status:</strong>
  <%= @line_item.status %>
</p>

<p>
  <strong>Record type:</strong>
  <%= @line_item.record_type %>
</p>

<p>
  <strong>Mid:</strong>
  <%= @line_item.mid %>
</p>

<p>
  <strong>Model:</strong>
  <%= @line_item.model %>
</p>

<p>
  <strong>Order:</strong>
  <%= @line_item.order %>
</p>

<p>
  <strong>Cart:</strong>
  <%= @line_item.cart %>
</p>

<%= link_to 'Edit', edit_line_item_path(@line_item) %> |
<%= link_to 'Back', line_items_path %>